module.exports = async function () {
    await Product.destroy({});

    await Product.createEach([
        { name: 'Laptop', price: 1200, description: 'Powerful laptop' },
        { name: 'Mouse', price: 25, description: 'Wireless mouse' },
        { name: 'Keyboard', price: 40, description: 'Mechanical keyboard' },
        { name: 'Monitor', price: 200, description: '24-inch Full HD monitor' },
        { name: 'USB-C Cable', price: 10, description: 'Durable USB-C charging cable' },
        { name: 'Webcam', price: 70, description: 'HD webcam for video calls' },
        { name: 'Desk Lamp', price: 35, description: 'LED desk lamp with adjustable brightness' },
        { name: 'External Hard Drive', price: 90, description: '1TB portable external hard drive' },
        { name: 'Smartphone', price: 800, description: 'Latest model smartphone' },
        { name: 'Bluetooth Speaker', price: 60, description: 'Portable Bluetooth speaker' },
        { name: 'Tablet', price: 500, description: '10-inch Android tablet' },
        { name: 'Printer', price: 150, description: 'Wireless color printer' },
        { name: 'Router', price: 80, description: 'Dual-band WiFi router' },
        { name: 'Headphones', price: 100, description: 'Noise-cancelling headphones' },
        { name: 'Microphone', price: 55, description: 'USB condenser microphone' },
        { name: 'Smartwatch', price: 250, description: 'Fitness tracking smartwatch' },
        { name: 'Projector', price: 300, description: 'HD home projector' },
        { name: 'Graphics Tablet', price: 120, description: 'Drawing graphics tablet' },
        { name: 'Power Bank', price: 45, description: '10000mAh portable power bank' },
        { name: 'Gaming Mouse', price: 60, description: 'RGB gaming mouse' },
        { name: 'VR Headset', price: 400, description: 'Virtual reality headset' },
        { name: 'Smart Light Bulb', price: 20, description: 'WiFi smart LED bulb' },
        { name: 'Fitness Tracker', price: 70, description: 'Waterproof fitness tracker' },
        { name: 'Portable SSD', price: 130, description: '500GB portable SSD' },
        { name: 'Wireless Charger', price: 30, description: 'Fast wireless charging pad' },
        { name: 'Laptop Stand', price: 25, description: 'Adjustable aluminum laptop stand' },
        { name: 'Ergonomic Chair', price: 220, description: 'Ergonomic office chair' },
        { name: 'Smart Plug', price: 18, description: 'WiFi smart plug' },
        { name: 'Action Camera', price: 180, description: '4K waterproof action camera' },
        { name: 'Bluetooth Earbuds', price: 90, description: 'True wireless earbuds' },
        { name: 'Desktop PC', price: 950, description: 'High performance desktop PC' },
        { name: 'Photo Printer', price: 170, description: 'Compact photo printer' },
        { name: 'Smart Thermostat', price: 120, description: 'WiFi smart thermostat' },
        { name: 'Streaming Stick', price: 50, description: '4K streaming media stick' },
        { name: 'Surge Protector', price: 22, description: '6-outlet surge protector' },
        { name: 'Wireless Presenter', price: 28, description: 'USB wireless presenter' },
        { name: 'Portable Monitor', price: 210, description: '15.6-inch portable monitor' },
        { name: 'Laptop Backpack', price: 55, description: 'Water-resistant laptop backpack' },
        { name: 'Smart Doorbell', price: 140, description: 'Video smart doorbell' },
        { name: 'USB Hub', price: 35, description: '7-port USB 3.0 hub' },
        { name: 'Mechanical Pencil', price: 5, description: '0.5mm mechanical pencil' },
        { name: 'Drawing Tablet', price: 110, description: 'Digital drawing tablet' },
        { name: 'Smart Scale', price: 60, description: 'Bluetooth smart scale' },
        { name: 'Noise Machine', price: 40, description: 'White noise sound machine' },
        { name: 'WiFi Extender', price: 45, description: 'Dual-band WiFi extender' },
        { name: 'Smart Lock', price: 180, description: 'Keyless smart lock' },
        { name: 'Dash Cam', price: 95, description: 'Full HD dash camera' },
        { name: 'Photo Scanner', price: 130, description: 'High-res photo scanner' },
        { name: 'Label Maker', price: 38, description: 'Portable label maker' },
        { name: 'Smart TV', price: 600, description: '50-inch 4K smart TV' },
        { name: 'Electric Kettle', price: 35, description: 'Stainless steel electric kettle' },
        { name: 'Coffee Maker', price: 80, description: 'Programmable coffee maker' },
        { name: 'Air Purifier', price: 150, description: 'HEPA air purifier' },
        { name: 'Robot Vacuum', price: 320, description: 'Smart robot vacuum cleaner' },
        { name: 'Bluetooth Adapter', price: 15, description: 'USB Bluetooth adapter' },
        { name: 'Smart Fan', price: 90, description: 'WiFi enabled smart fan' },
        { name: 'Wireless Keyboard', price: 45, description: 'Slim wireless keyboard' },
        { name: 'Smart Camera', price: 110, description: 'WiFi security camera' },
        { name: '3D Printer', price: 450, description: 'Desktop 3D printer' },
        { name: 'Electric Scooter', price: 350, description: 'Foldable electric scooter' },
        { name: 'Smart Glasses', price: 220, description: 'Bluetooth smart glasses' },
        { name: 'Portable Projector', price: 250, description: 'Mini portable projector' },
        { name: 'Smart Alarm Clock', price: 60, description: 'WiFi smart alarm clock' },
        { name: 'Wireless Mouse', price: 30, description: 'Ergonomic wireless mouse' },
        { name: 'Gaming Keyboard', price: 85, description: 'RGB gaming keyboard' },
        { name: 'Smart Switch', price: 25, description: 'WiFi smart switch' },
        { name: 'Electric Toothbrush', price: 55, description: 'Rechargeable electric toothbrush' },
        { name: 'Smart Water Bottle', price: 40, description: 'Hydration tracking smart bottle' },
        { name: 'Portable Charger', price: 35, description: '5000mAh portable charger' },
        { name: 'Smart Pen', price: 70, description: 'Bluetooth smart pen' },
        { name: 'Wireless Earphones', price: 65, description: 'Bluetooth wireless earphones' },
        { name: 'Smart Mirror', price: 300, description: 'Touchscreen smart mirror' },
        { name: 'Smart Oven', price: 400, description: 'WiFi connected smart oven' },
        { name: 'Smart Fridge', price: 1200, description: 'Large smart refrigerator' },
        { name: 'Smart Washer', price: 800, description: 'WiFi enabled washing machine' },
        { name: 'Smart Dryer', price: 750, description: 'WiFi enabled dryer' },
        { name: 'Smart Air Conditioner', price: 650, description: 'WiFi smart air conditioner' },
        { name: 'Smart Heater', price: 200, description: 'WiFi smart heater' },
        { name: 'Smart Blinds', price: 350, description: 'Remote controlled smart blinds' },
        { name: 'Smart Sprinkler', price: 180, description: 'WiFi smart sprinkler system' },
        { name: 'Smart Garage Opener', price: 160, description: 'WiFi garage door opener' },
        { name: 'Smart Smoke Detector', price: 90, description: 'WiFi smoke detector' },
        { name: 'Smart Carbon Monoxide Detector', price: 95, description: 'WiFi CO detector' },
        { name: 'Smart Pet Feeder', price: 130, description: 'Automatic smart pet feeder' },
        { name: 'Smart Pet Camera', price: 120, description: 'WiFi pet camera' },
        { name: 'Smart Plant Sensor', price: 45, description: 'Bluetooth plant sensor' },
        { name: 'Smart Baby Monitor', price: 150, description: 'WiFi baby monitor' },
        { name: 'Smart Scale Pro', price: 80, description: 'Advanced smart scale' },
        { name: 'Smart Bike Lock', price: 70, description: 'Bluetooth bike lock' },
        { name: 'Smart Luggage', price: 200, description: 'GPS enabled smart luggage' },
        { name: 'Smart Wallet', price: 60, description: 'RFID blocking smart wallet' },
        { name: 'Smart Mug', price: 50, description: 'Temperature control smart mug' },
        { name: 'Smart Key Finder', price: 25, description: 'Bluetooth key finder' },
        { name: 'Smart Thermometer', price: 35, description: 'Bluetooth smart thermometer' },
        { name: 'Smart Blood Pressure Monitor', price: 90, description: 'Bluetooth BP monitor' },
        { name: 'Smart Glucometer', price: 100, description: 'Bluetooth smart glucometer' },
        { name: 'Smart Pulse Oximeter', price: 60, description: 'Bluetooth pulse oximeter' },
        { name: 'Smart Jump Rope', price: 40, description: 'Bluetooth smart jump rope' }
    ]);

    console.log('Seed thành công dữ liệu sản phẩm mẫu');
};
